pipeline {
    agent any

   
    stages {
        stage('Git') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/hwafa/timesheetproject.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('MVN Nexus') {
            steps {
                sh 'mvn install -Dmaven.test.skip=true'
            }
        }
        stage('Check File Structure') {
    steps {
        sh 'ls -la'
    }
}
stage('Debug') {
    steps {
        sh 'find . -name "Dockerfile"'
    }
}

      stage('Build Image') {
            steps {
                sh 'sh docker build -t houdachaanbi/timesheet-devops:1.0.0 -f ./Dockerfile .'

            }
        }
        stage('Deploy Image') {
            steps {
                sh 'docker push houdachaanbi/timesheet-devops:1.0.0'
            }
        }
    }
}
