pipeline {
    agent any

    stages {
        stage('Git') {
            steps {
                git branch: 'master', 
                    url: 'https://github.com/HOUDA-18/timesheetprojectDevops.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'atliersonar'
                    
                    withSonarQubeEnv('atliersonar') {
                        // Correction : Supprimer les antislashs et utiliser des guillemets simples
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=atliersonar \
                            -Dsonar.sources=src \
                            -Dsonar.projectName=atliersonar
                        """
                    }
                }
            }
        }
    }
}
