pipeline {
    agent any

    stages {
        stage('Git') {
            steps {
                git branch: 'master', url: 'https://github.com/hwafa/timesheetproject.git'
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script {
                    // Remplacez 'SonarQube Scanner' par le nom exact défini dans la configuration de Jenkins.
                    def scannerHome = tool 'SonarQube Scanner' 
                    // Remplacez 'SonarQube' par le nom de votre serveur SonarQube configuré (dans Manage Jenkins > Configure System)
                    withSonarQubeEnv('SonarQube') { 
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }
    }
}
